// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"ride-hail/pkg/uuid"
)

type Coordinate struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EntityID        uuid.UUID
	EntityType      string
	Address         string
	Latitude        pgtype.Numeric
	Longitude       pgtype.Numeric
	FareAmount      pgtype.Numeric
	DistanceKm      pgtype.Numeric
	DurationMinutes pgtype.Int4
	IsCurrent       pgtype.Bool
}

type DriverSession struct {
	ID            uuid.UUID
	DriverID      uuid.UUID
	StartedAt     time.Time
	EndedAt       *time.Time
	TotalRides    pgtype.Int4
	TotalEarnings pgtype.Numeric
}

type Ride struct {
	ID                      uuid.UUID
	CreatedAt               time.Time
	UpdatedAt               time.Time
	RideNumber              string
	PassengerID             uuid.UUID
	DriverID                uuid.UUID
	VehicleType             *string
	Status                  *string
	Priority                pgtype.Int4
	RequestedAt             *time.Time
	MatchedAt               *time.Time
	ArrivedAt               *time.Time
	StartedAt               *time.Time
	CompletedAt             *time.Time
	CancelledAt             *time.Time
	CancellationReason      *string
	EstimatedFare           pgtype.Numeric
	FinalFare               pgtype.Numeric
	PickupCoordinateID      uuid.UUID
	DestinationCoordinateID uuid.UUID
}

type RideCounter struct {
	Day     time.Time
	Counter int32
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	Role         string
	Status       string
	PasswordHash string
	Salt         string
	Attrs        any
}
