// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"ride-hail/pkg/uuid"
)

type Querier interface {
	CancelRide(ctx context.Context, arg CancelRideParams) (Ride, error)
	CreateCoordinate(ctx context.Context, arg CreateCoordinateParams) (Coordinate, error)
	CreateCoordinateForDriver(ctx context.Context, arg CreateCoordinateForDriverParams) (Coordinate, error)
	CreateDriverSession(ctx context.Context, driverID uuid.UUID) (DriverSession, error)
	CreateLocationHistory(ctx context.Context, arg CreateLocationHistoryParams) error
	CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error)
	CreateRideEvent(ctx context.Context, arg CreateRideEventParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EndDriverSession(ctx context.Context, arg EndDriverSessionParams) (DriverSession, error)
	FindNearbyDrivers(ctx context.Context, arg FindNearbyDriversParams) ([]FindNearbyDriversRow, error)
	// Admin Service Queries
	GetActiveRidesCount(ctx context.Context) (int64, error)
	GetActiveRidesPaginated(ctx context.Context, arg GetActiveRidesPaginatedParams) ([]GetActiveRidesPaginatedRow, error)
	GetActiveRidesTotalCount(ctx context.Context) (int64, error)
	GetAvailableDriversCount(ctx context.Context) (int64, error)
	GetAverageRideDuration(ctx context.Context) (interface{}, error)
	GetAverageWaitTime(ctx context.Context) (interface{}, error)
	GetBusyDriversCount(ctx context.Context) (int64, error)
	GetCancellationRate(ctx context.Context) (interface{}, error)
	GetCurrentDriverSession(ctx context.Context, driverID uuid.UUID) (DriverSession, error)
	GetDriverCurrentLocation(ctx context.Context, entityID uuid.UUID) (Coordinate, error)
	GetDriverDistributionByVehicleType(ctx context.Context) ([]GetDriverDistributionByVehicleTypeRow, error)
	GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error)
	GetTodayRevenue(ctx context.Context) (interface{}, error)
	GetTodayRidesCount(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IncrementRideCounter(ctx context.Context, date time.Time) (RideCounter, error)
	MarkDriverCoordinatesAsOld(ctx context.Context, entityID uuid.UUID) error
	UpdateDriverRide(ctx context.Context, id uuid.UUID) error
	UpdateDriverStats(ctx context.Context, arg UpdateDriverStatsParams) error
	UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) error
	UpdateRideCompleted(ctx context.Context, arg UpdateRideCompletedParams) (Ride, error)
	UpdateRideMatched(ctx context.Context, arg UpdateRideMatchedParams) error
	UpdateRideStarted(ctx context.Context, id uuid.UUID) error
	UpdateRideStatus(ctx context.Context, arg UpdateRideStatusParams) error
	UpdateSessionStats(ctx context.Context, arg UpdateSessionStatsParams) error
}

var _ Querier = (*Queries)(nil)
