// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ride.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"ride-hail/pkg/uuid"
)

const cancelRide = `-- name: CancelRide :one
update rides
set
    status = 'CANCELLED',
    cancellation_reason = $2,
    cancelled_at = now(),
    updated_at = now()
where id = $1
  and status != 'COMPLETED'
  and status != 'CANCELLED'
returning id, created_at, updated_at, ride_number, passenger_id, driver_id, vehicle_type, status, priority, requested_at, matched_at, arrived_at, started_at, completed_at, cancelled_at, cancellation_reason, estimated_fare, final_fare, pickup_coordinate_id, destination_coordinate_id
`

type CancelRideParams struct {
	ID                 uuid.UUID
	CancellationReason *string
}

func (q *Queries) CancelRide(ctx context.Context, arg CancelRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, cancelRide, arg.ID, arg.CancellationReason)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RideNumber,
		&i.PassengerID,
		&i.DriverID,
		&i.VehicleType,
		&i.Status,
		&i.Priority,
		&i.RequestedAt,
		&i.MatchedAt,
		&i.ArrivedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.EstimatedFare,
		&i.FinalFare,
		&i.PickupCoordinateID,
		&i.DestinationCoordinateID,
	)
	return i, err
}

const createCoordinate = `-- name: CreateCoordinate :one
insert into coordinates (
    entity_id,
    entity_type,
    address,
    latitude,
    longitude,
    distance_km,
    duration_minutes,
    fare_amount,
    is_current
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, false
)
returning id, created_at, updated_at, entity_id, entity_type, address, latitude, longitude, fare_amount, distance_km, duration_minutes, is_current
`

type CreateCoordinateParams struct {
	EntityID        uuid.UUID
	EntityType      string
	Address         string
	Latitude        pgtype.Numeric
	Longitude       pgtype.Numeric
	DistanceKm      pgtype.Numeric
	DurationMinutes pgtype.Int4
	FareAmount      pgtype.Numeric
}

func (q *Queries) CreateCoordinate(ctx context.Context, arg CreateCoordinateParams) (Coordinate, error) {
	row := q.db.QueryRow(ctx, createCoordinate,
		arg.EntityID,
		arg.EntityType,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.DistanceKm,
		arg.DurationMinutes,
		arg.FareAmount,
	)
	var i Coordinate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntityID,
		&i.EntityType,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.FareAmount,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.IsCurrent,
	)
	return i, err
}

const createRide = `-- name: CreateRide :one
insert into rides (
    ride_number,
    passenger_id,
    vehicle_type,
    status,
    estimated_fare,
    pickup_coordinate_id,
    destination_coordinate_id
) values (
    $1,
    $2,
    $3,
    'REQUESTED',
    $4,
    $5,
    $6
)
returning id, created_at, updated_at, ride_number, passenger_id, driver_id, vehicle_type, status, priority, requested_at, matched_at, arrived_at, started_at, completed_at, cancelled_at, cancellation_reason, estimated_fare, final_fare, pickup_coordinate_id, destination_coordinate_id
`

type CreateRideParams struct {
	RideNumber              string
	PassengerID             uuid.UUID
	VehicleType             *string
	EstimatedFare           pgtype.Numeric
	PickupCoordinateID      uuid.UUID
	DestinationCoordinateID uuid.UUID
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.RideNumber,
		arg.PassengerID,
		arg.VehicleType,
		arg.EstimatedFare,
		arg.PickupCoordinateID,
		arg.DestinationCoordinateID,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RideNumber,
		&i.PassengerID,
		&i.DriverID,
		&i.VehicleType,
		&i.Status,
		&i.Priority,
		&i.RequestedAt,
		&i.MatchedAt,
		&i.ArrivedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.EstimatedFare,
		&i.FinalFare,
		&i.PickupCoordinateID,
		&i.DestinationCoordinateID,
	)
	return i, err
}

const createRideEvent = `-- name: CreateRideEvent :exec
insert into ride_events (
    ride_id,
    event_type,
    event_data
) values (
    $1, $2, $3
)
`

type CreateRideEventParams struct {
	RideID    uuid.UUID
	EventType string
	EventData []byte
}

func (q *Queries) CreateRideEvent(ctx context.Context, arg CreateRideEventParams) error {
	_, err := q.db.Exec(ctx, createRideEvent, arg.RideID, arg.EventType, arg.EventData)
	return err
}

const getRideByID = `-- name: GetRideByID :one
select id, created_at, updated_at, ride_number, passenger_id, driver_id, vehicle_type, status, priority, requested_at, matched_at, arrived_at, started_at, completed_at, cancelled_at, cancellation_reason, estimated_fare, final_fare, pickup_coordinate_id, destination_coordinate_id from rides
where id = $1
limit 1
`

func (q *Queries) GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RideNumber,
		&i.PassengerID,
		&i.DriverID,
		&i.VehicleType,
		&i.Status,
		&i.Priority,
		&i.RequestedAt,
		&i.MatchedAt,
		&i.ArrivedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.EstimatedFare,
		&i.FinalFare,
		&i.PickupCoordinateID,
		&i.DestinationCoordinateID,
	)
	return i, err
}

const incrementRideCounter = `-- name: IncrementRideCounter :one
INSERT INTO ride_counters (day, counter)
VALUES ($1::date, 1)
ON CONFLICT (day) DO UPDATE
  SET counter = ride_counters.counter + 1
RETURNING day,counter
`

func (q *Queries) IncrementRideCounter(ctx context.Context, date time.Time) (RideCounter, error) {
	row := q.db.QueryRow(ctx, incrementRideCounter, date)
	var i RideCounter
	err := row.Scan(&i.Day, &i.Counter)
	return i, err
}
