// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        email,
        role,
        status,
        password_hash,
        salt,
        attrs
    )
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_at, updated_at, email, role, status, password_hash, salt, attrs
`

type CreateUserParams struct {
	Email        string
	Role         string
	Status       string
	PasswordHash string
	Salt         string
	Attrs        any
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.PasswordHash,
		arg.Salt,
		arg.Attrs,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.Salt,
		&i.Attrs,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    created_at,
    updated_at,
    email,
    role,
    status,
    password_hash,
    salt,
    attrs
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.Salt,
		&i.Attrs,
	)
	return i, err
}
